# Generated by Django 3.2 on 2022-08-23 19:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('heading', models.CharField(max_length=500)),
                ('body', models.TextField(max_length=500)),
                ('article_src_link', models.URLField(max_length=1000, unique=True)),
                ('author', models.CharField(max_length=500)),
                ('publisher', models.CharField(max_length=200, null=True)),
                ('published_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
