version: "3.8"

services:
    esearch:
        container_name: search
        image: elasticsearch:7.14.2
        environment:
        - discovery.type=single-node
        ports:
        - "9200:9200"